from ccxt.base.types import Entry

class ImplicitAPI:
    public_get_api_status = publicGetApiStatus = Entry('api/status', 'public', 'GET', {'cost': 0.1})
    public_get_api_servertime = publicGetApiServertime = Entry('api/v3/servertime', 'public', 'GET', {'cost': 0.1})
    public_get_api_market_symbols = publicGetApiMarketSymbols = Entry('api/market/symbols', 'public', 'GET', {'cost': 0.1})
    public_get_api_market_ticker = publicGetApiMarketTicker = Entry('api/market/ticker', 'public', 'GET', {'cost': 0.1})
    public_get_api_market_trades = publicGetApiMarketTrades = Entry('api/market/trades', 'public', 'GET', {'cost': 0.1})
    public_get_api_market_bids = publicGetApiMarketBids = Entry('api/market/bids', 'public', 'GET', {'cost': 0.1})
    public_get_api_market_asks = publicGetApiMarketAsks = Entry('api/market/asks', 'public', 'GET', {'cost': 0.1})
    public_get_api_market_books = publicGetApiMarketBooks = Entry('api/market/books', 'public', 'GET', {'cost': 0.1})
    public_get_api_market_depth = publicGetApiMarketDepth = Entry('api/market/depth', 'public', 'GET', {'cost': 0.1})
    public_get_tradingview_history = publicGetTradingviewHistory = Entry('tradingview/history', 'public', 'GET', {'cost': 0.1})
    private_post_api_market_wallet = privatePostApiMarketWallet = Entry('api/v3/market/wallet', 'private', 'POST', {'cost': 0.1})
    private_post_api_market_balances = privatePostApiMarketBalances = Entry('api/v3/market/balances', 'private', 'POST', {'cost': 0.1})
    private_post_api_market_place_bid = privatePostApiMarketPlaceBid = Entry('api/v3/market/place-bid', 'private', 'POST', {'cost': 0.1})
    private_post_api_market_place_ask = privatePostApiMarketPlaceAsk = Entry('api/v3/market/place-ask', 'private', 'POST', {'cost': 0.1})
    private_post_api_market_cancel_order = privatePostApiMarketCancelOrder = Entry('api/v3/market/cancel-order', 'private', 'POST', {'cost': 0.1})
    private_get_api_market_my_open_orders = privateGetApiMarketMyOpenOrders = Entry('api/v3/market/my-open-orders', 'private', 'GET', {'cost': 0.1})
    private_get_api_market_my_order_history = privateGetApiMarketMyOrderHistory = Entry('api/v3/market/my-order-history', 'private', 'GET', {'cost': 0.1})
    private_get_api_market_order_info = privateGetApiMarketOrderInfo = Entry('api/v3/market/order-info', 'private', 'GET', {'cost': 0.1})
    private_post_api_crypto_addresses = privatePostApiCryptoAddresses = Entry('api/v3/crypto/addresses', 'private', 'POST', {'cost': 0.1})
    private_post_api_crypto_withdraw = privatePostApiCryptoWithdraw = Entry('api/v3/crypto/withdraw', 'private', 'POST', {'cost': 0.1})
    private_post_api_crypto_deposit_history = privatePostApiCryptoDepositHistory = Entry('api/v3/crypto/deposit-history', 'private', 'POST', {'cost': 0.1})
    private_post_api_crypto_withdraw_history = privatePostApiCryptoWithdrawHistory = Entry('api/v3/crypto/withdraw-history', 'private', 'POST', {'cost': 0.1})
    private_post_api_crypto_generate_address = privatePostApiCryptoGenerateAddress = Entry('api/v3/crypto/generate-address', 'private', 'POST', {'cost': 0.1})
    private_post_api_fiat_accounts = privatePostApiFiatAccounts = Entry('api/v3/fiat/accounts', 'private', 'POST', {'cost': 0.1})
    private_post_api_fiat_withdraw = privatePostApiFiatWithdraw = Entry('api/v3/fiat/withdraw', 'private', 'POST', {'cost': 0.1})
    private_post_api_fiat_deposit_history = privatePostApiFiatDepositHistory = Entry('api/v3/fiat/deposit-history', 'private', 'POST', {'cost': 0.1})
    private_post_api_fiat_withdraw_history = privatePostApiFiatWithdrawHistory = Entry('api/v3/fiat/withdraw-history', 'private', 'POST', {'cost': 0.1})
    private_post_api_market_wstoken = privatePostApiMarketWstoken = Entry('api/v3/market/wstoken', 'private', 'POST', {'cost': 0.1})
    private_post_api_user_limits = privatePostApiUserLimits = Entry('api/v3/user/limits', 'private', 'POST', {'cost': 0.1})
    private_post_api_user_trading_credits = privatePostApiUserTradingCredits = Entry('api/v3/user/trading-credits', 'private', 'POST', {'cost': 0.1})
    private_post_api_crypto_internal_withdraw = privatePostApiCryptoInternalWithdraw = Entry('api/v3/crypto/internal-withdraw', 'private', 'POST', {'cost': 0.1})